version: '2'
services:
  plex:
    container_name: plex
    # Update to newest
    # docker pull plexinc/pms-docker:1.41.7.9823-59f304c16
    image: plexinc/pms-docker:1.41.7.9823-59f304c16
    restart: unless-stopped
    environment:
      - TZ=${TZONE}
      - PLEX_CLAIM=${CLAIM}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    network_mode: host
    volumes:
      - ${CONFIG_DIR}:/config
      - ${TRANSCODE_DIR}:/transcode
      - ${DATA_DIR}:/data
