services:
  # Torrent client
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${QBT_UID} # transmission
      - PGID=${QBT_GID} # plexapp
      - TZ=${PLEX_TZONE}
      - WEBUI_PORT=3489
      - TORRENTING_PORT=6881
    volumes:
      - ${QBT_CONFIG_DIR}:/config
      - ${ARR_TORRENT_DIR}:/data/torrents
    ports:
      - "3489:3489"             # Web UI
      - "6881:6881"             # BitTorrent port
      - "6881:6881/udp"
    restart: unless-stopped

  # Prowlarr - Indexer manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${PROWLARR_CONFIG_DIR}:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  # Overseerr - Request management
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${OVERSEERR_CONFIG_DIR}:/config
    ports:
      - "5055:5055"
    restart: unless-stopped


  # Sonarr - TV Shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${ARR_DATA_DIR}:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  # Radarr - Movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${ARR_DATA_DIR}:/data
    ports:
      - "7878:7878"
    restart: unless-stopped


  # Lidarr - Music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${LIDARR_CONFIG_DIR}:/config
      - ${ARR_DATA_DIR}:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  # Readarr - Books
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${READARR_CONFIG_DIR}:/config
      - ${ARR_DATA_DIR}:/data
    ports:
      - "8787:8787"
    restart: unless-stopped


  # Bazarr - Subtitles
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PLEX_UID}
      - PGID=${PLEX_GID}
      - UMASK=002
      - TZ=${PLEX_TZONE}
    volumes:
      - ${BAZARR_CONFIG_DIR}:/config
      - ${ARR_DATA_DIR}:/data
    ports:
      - "6767:6767"
    restart: unless-stopped

networks:
  default:
    name: arr-stack
