version: '2'
services:
  plex2:
    container_name: plex2
    # Update to newest
    # docker pull plexinc/pms-docker:1.41.7.9823-59f304c16
    image: plexinc/pms-docker:1.41.7.9823-59f304c16
    restart: unless-stopped
      # user: "${PLEX_UID}:${PLEX_GID}"
    environment:
      - TZ=${PLEX_TZONE}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    network_mode: host
    volumes:
      - ${PLEX_CONFIG_DIR}:/config
      - ${PLEX_TRANSCODE_DIR}:/transcode
      - ${PLEX_DATA_DIR}:/data
